version: 1.0.{build}
clone_depth: 1
clone_folder: C:\work\src\github.com\therecipe\qt
install:
- cmd: >-
    set PATH=%PATH%;C:\Qt\Tools\mingw530_32\bin

    set GOPATH=C:\work


    set QT=qt-unified-windows-x86-online.exe

    curl -sL --retry 10 --retry-delay 10 -o %TMP%\%QT% https://download.qt.io/official_releases/online_installers/%QT%

    %TMP%\%QT% --script %GOPATH%\src\github.com\therecipe\qt\internal\ci\iscript.qs

    del %TMP%\%QT% /Q


    set SDK=sdk-tools-windows-3859397.zip

    curl -sL --retry 10 --retry-delay 10 -o %TMP%\%SDK% https://dl.google.com/android/repository/%SDK%

    7z x %TMP%\%SDK% -oC:\android-sdk-windows\

    del %TMP%\%SDK% /Q


    C:\android-sdk-windows\tools\bin\sdkmanager.bat --list --verbose

    echo y | C:\android-sdk-windows\tools\bin\sdkmanager.bat "platform-tools" "build-tools;26.0.0" "platforms;android-25"

    C:\android-sdk-windows\tools\bin\sdkmanager.bat --update

    set NDK=android-ndk-r14b-windows-x86_64.zip

    curl -sL --retry 10 --retry-delay 10 -o %TMP%\%NDK% https://dl.google.com/android/repository/%NDK%

    7z x %TMP%\%NDK% -oC:\

    del %TMP%\%NDK% /Q
build_script:
- cmd: >-
    go get -v github.com/therecipe/qt/cmd/...

    %GOPATH%\bin\qtsetup full desktop

    %GOPATH%\bin\qtsetup full android
